<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ingresar</name>
   <tag></tag>
   <elementGuidId>f6902635-b23e-4977-9106-42804790a6f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card.sticky-action.ma-card-reveal-content > div.card-action > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_10008870502834352241_catch']/div/div/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ingresar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84faaaac-a057-4e65-b872-bd2de92a1962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ords/r/portal/sladm/1?session=703438690561240</value>
      <webElementGuid>494b9166-32f7-42b2-adac-df8578eab3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>2206b92a-01bc-42f2-8939-b6068312b3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_10008870502834352241_catch&quot;)/div[@class=&quot;ma-report--cards ma-card-hoverable ma-card-reveal ma-card-col-4&quot;]/div[@class=&quot;ma-card-col&quot;]/div[@class=&quot;card sticky-action ma-card-reveal-content&quot;]/div[@class=&quot;card-action&quot;]/a[1]</value>
      <webElementGuid>aa3d77f5-7148-43d6-abd2-12df8122d2a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_10008870502834352241_catch']/div/div/div[2]/div[3]/a</value>
      <webElementGuid>f1e0c736-8971-43e1-9682-d923364f704c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ingresar')])[2]</value>
      <webElementGuid>7b48d3a1-4632-4fba-9cf1-b56636c1b352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Admin'])[2]/following::a[1]</value>
      <webElementGuid>b415ffca-178a-4ff8-810d-c9be150b38e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar'])[1]/following::a[2]</value>
      <webElementGuid>1ce1bc5d-9ea9-45c6-828c-c78f623f4664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Admin'])[3]/preceding::a[2]</value>
      <webElementGuid>9ee76abd-bce1-4f43-b544-a43bdbc02e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Apps'])[2]/preceding::a[4]</value>
      <webElementGuid>5381cce0-9cb9-4b38-8162-0256d1ed2d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ords/r/portal/sladm/1?session=703438690561240')])[3]</value>
      <webElementGuid>d47492ab-a384-41e7-9e2a-2258b67d3946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>dd1dc6ba-055f-43b6-9d17-32b79361fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ords/r/portal/sladm/1?session=703438690561240' and (text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>7cfb09ed-39b4-498e-8960-115d43ae5ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
